[alias]
rel = "build --release" #--example sqr"
inst = "install --path ." #--example sqr"
clip = "clippy --release" #--example sqr"
tst = "test --release"
pub = "publish"

[build]
target = "x86_64-unknown-linux-musl"

[install]
target = "x86_64-unknown-linux-musl"

[publish]
target = "x86_64-unknown-linux-musl"

[clippy]
target = "x86_64-unknown-linux-musl"
