[alias]
rel = "build --release --example rqr"
inst = "install --path . --example rqr"
clip = "clippy --release --example rqr"
pub = "publish"

[build]
target = "x86_64-unknown-linux-musl"

[install]
target = "x86_64-unknown-linux-musl"

[publish]
target = "x86_64-unknown-linux-musl"

[clippy]
target = "x86_64-unknown-linux-musl"
